### ISSUE TITLE
rsyslog dependancies

### ISSUE THREAD

**Issue by jehane** [tskirvin/puppet-puppet#4]
Hi, 

saz-rsyslog is depreciated (https://forge.puppet.com/saz/rsyslog) and is replaced by puppet-rsyslog (https://forge.puppet.com/puppet/rsyslog ) 
Can you update your module to reflect this change ? 

Regards

**Comment by tskirvin** [comment]
This doesn't appear to be even close to a 1:1 replacement; I was very fond of rsyslog::snippet for starters.

I'll ping the upstream project.

**Comment by tskirvin** [comment]
That said, I also updated my module to not depend on your module anymore.  (I'm managing rsyslog.d files directly now, which isn't great but oh well.)

**Comment by jehane** [comment]
Thanks
